server:
  port: 10001
spring:
  application:
    name: gulimall-product
  redis:
    host: 39.97.224.239
    port: 6379
    password: redis
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.224.239:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false  # 关闭缓存
  cache:
    type: redis
    redis:
      time-to-live: 3600000
#      key-prefix: CACHE_  # 默认为 分区名
      use-key-prefix: true
      cache-null-values: true # 是否缓存空值 ，防止缓存穿透
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    banner: true
    db-config:
      id-type: auto
      # 1、 全局逻辑删除 配置  2、配置逻辑删除组件（看官方文档） 3、字段加 逻辑删除 注解
      logic-delete-value: 1 #  1 表示已被删除
      logic-not-delete-value: 0 # 0 为未被删除

logging:
  level:
    com.gulimall.product.dao: debug
#swagger:
#  enabled: true
#  title: 用户服务
#  base-package: com.gulimall.product.controller
#  version: V2.0
#  description: 用户服务
#  license: Apache License, Version 2.0
#  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
#  terms-of-service-url: http://localhost:8002/doc.html
#  contact: xxxxxxxxxxxx@gmail.com
#  authorization: #有auth2 并使用以前的swagger-ui
#    key-name: Authorization

gulimall:
  thread:
    core-size: 5
    max-size: 30
    keep-alive-time: 20
