package com.gulimall.pay.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.gulimall.pay.entity.PayDo;
import com.gulimall.pay.vo.MallOrderTransOsSyncVo;

public interface PayDao extends BaseMapper<PayDo> {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_pay
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_pay
	 *
	 * @mbg.generated
	 */
	int insert(PayDo record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_pay
	 *
	 * @mbg.generated
	 */
	int insertSelective(PayDo record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_pay
	 *
	 * @mbg.generated
	 */
	PayDo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_pay
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PayDo record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_pay
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PayDo record);

	List<MallOrderTransOsSyncVo> selectOsSyncOrderData(@Param("orderIdList") List<String> orderIdList);

	/**
	 * 根据订单ids查询支付信息， 
	 * @param orderIds
	 * @return
	 */
	List<PayDo> batchQueryByOrderIds(List<String> orderIds);
}
