package com.gulimall.pay.dao;

import org.apache.ibatis.annotations.Param;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.gulimall.pay.entity.TransDo;

public interface TransDao extends BaseMapper<TransDo> {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_trans
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_trans
	 *
	 * @mbg.generated
	 */
	int insert(TransDo record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_trans
	 *
	 * @mbg.generated
	 */
	int insertSelective(TransDo record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_trans
	 *
	 * @mbg.generated
	 */
	TransDo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_trans
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TransDo record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table foreo_trans
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TransDo record);

	TransDo selectByThirdReqId(@Param("thirdReqId") String thirdReqId);

	TransDo selectTransByOrderId(@Param("orderId") String orderId, @Param("payStatus") String payStatus);
}
