server:
  port: 20000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 39.97.224.239
    password: redis
    port: 6379
    database: 0
