package com.gulimall.pay.entity;

import java.util.Date;

public class PayDo {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_pay.id
	 *
	 * @mbg.generated
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_pay.order_id
	 *
	 * @mbg.generated
	 */
	private String orderId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_pay.order_amount
	 *
	 * @mbg.generated
	 */
	private String orderAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_pay.pay_channel
	 *
	 * @mbg.generated
	 */
	private String payChannel;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_pay.pay_type
	 *
	 * @mbg.generated
	 */
	private String payType;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_pay.pay_date
	 *
	 * @mbg.generated
	 */
	private Date payDate;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_pay.pay_status
	 *
	 * @mbg.generated
	 */
	private String payStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_pay.create_date
	 *
	 * @mbg.generated
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_pay.id
	 *
	 * @return the value of foreo_pay.id
	 *
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_pay.id
	 *
	 * @param id the value for foreo_pay.id
	 *
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_pay.order_id
	 *
	 * @return the value of foreo_pay.order_id
	 *
	 * @mbg.generated
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_pay.order_id
	 *
	 * @param orderId the value for foreo_pay.order_id
	 *
	 * @mbg.generated
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_pay.order_amount
	 *
	 * @return the value of foreo_pay.order_amount
	 *
	 * @mbg.generated
	 */
	public String getOrderAmount() {
		return orderAmount;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_pay.order_amount
	 *
	 * @param orderAmount the value for foreo_pay.order_amount
	 *
	 * @mbg.generated
	 */
	public void setOrderAmount(String orderAmount) {
		this.orderAmount = orderAmount == null ? null : orderAmount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_pay.pay_channel
	 *
	 * @return the value of foreo_pay.pay_channel
	 *
	 * @mbg.generated
	 */
	public String getPayChannel() {
		return payChannel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_pay.pay_channel
	 *
	 * @param payChannel the value for foreo_pay.pay_channel
	 *
	 * @mbg.generated
	 */
	public void setPayChannel(String payChannel) {
		this.payChannel = payChannel == null ? null : payChannel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_pay.pay_type
	 *
	 * @return the value of foreo_pay.pay_type
	 *
	 * @mbg.generated
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_pay.pay_type
	 *
	 * @param payType the value for foreo_pay.pay_type
	 *
	 * @mbg.generated
	 */
	public void setPayType(String payType) {
		this.payType = payType == null ? null : payType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_pay.pay_date
	 *
	 * @return the value of foreo_pay.pay_date
	 *
	 * @mbg.generated
	 */
	public Date getPayDate() {
		return payDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_pay.pay_date
	 *
	 * @param payDate the value for foreo_pay.pay_date
	 *
	 * @mbg.generated
	 */
	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_pay.pay_status
	 *
	 * @return the value of foreo_pay.pay_status
	 *
	 * @mbg.generated
	 */
	public String getPayStatus() {
		return payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_pay.pay_status
	 *
	 * @param payStatus the value for foreo_pay.pay_status
	 *
	 * @mbg.generated
	 */
	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus == null ? null : payStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_pay.create_date
	 *
	 * @return the value of foreo_pay.create_date
	 *
	 * @mbg.generated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_pay.create_date
	 *
	 * @param createDate the value for foreo_pay.create_date
	 *
	 * @mbg.generated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
