package com.gulimall.pay.entity;

import java.util.Date;

public class TransDo {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.id
	 *
	 * @mbg.generated
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.pay_id
	 *
	 * @mbg.generated
	 */
	private String payId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.refund_id
	 *
	 * @mbg.generated
	 */
	private String refundId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.trans_type
	 *
	 * @mbg.generated
	 */
	private String transType;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.trans_amount
	 *
	 * @mbg.generated
	 */
	private String transAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.trans_channel
	 *
	 * @mbg.generated
	 */
	private String transChannel;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.third_trade_req_id
	 *
	 * @mbg.generated
	 */
	private String thirdTradeReqId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.third_trade_res_id
	 *
	 * @mbg.generated
	 */
	private String thirdTradeResId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.third_trade_req_time
	 *
	 * @mbg.generated
	 */
	private Date thirdTradeReqTime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.third_trade_res_time
	 *
	 * @mbg.generated
	 */
	private Date thirdTradeResTime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.third_trade_callback_amount
	 *
	 * @mbg.generated
	 */
	private String thirdTradeCallbackAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.third_trade_callback_time
	 *
	 * @mbg.generated
	 */
	private Date thirdTradeCallbackTime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.create_time
	 *
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans.trans_status
	 *
	 * @mbg.generated
	 */
	private String transStatus;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.id
	 *
	 * @return the value of foreo_trans.id
	 *
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.id
	 *
	 * @param id the value for foreo_trans.id
	 *
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.pay_id
	 *
	 * @return the value of foreo_trans.pay_id
	 *
	 * @mbg.generated
	 */
	public String getPayId() {
		return payId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.pay_id
	 *
	 * @param payId the value for foreo_trans.pay_id
	 *
	 * @mbg.generated
	 */
	public void setPayId(String payId) {
		this.payId = payId == null ? null : payId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.refund_id
	 *
	 * @return the value of foreo_trans.refund_id
	 *
	 * @mbg.generated
	 */
	public String getRefundId() {
		return refundId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.refund_id
	 *
	 * @param refundId the value for foreo_trans.refund_id
	 *
	 * @mbg.generated
	 */
	public void setRefundId(String refundId) {
		this.refundId = refundId == null ? null : refundId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.trans_type
	 *
	 * @return the value of foreo_trans.trans_type
	 *
	 * @mbg.generated
	 */
	public String getTransType() {
		return transType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.trans_type
	 *
	 * @param transType the value for foreo_trans.trans_type
	 *
	 * @mbg.generated
	 */
	public void setTransType(String transType) {
		this.transType = transType == null ? null : transType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.trans_amount
	 *
	 * @return the value of foreo_trans.trans_amount
	 *
	 * @mbg.generated
	 */
	public String getTransAmount() {
		return transAmount;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.trans_amount
	 *
	 * @param transAmount the value for foreo_trans.trans_amount
	 *
	 * @mbg.generated
	 */
	public void setTransAmount(String transAmount) {
		this.transAmount = transAmount == null ? null : transAmount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.trans_channel
	 *
	 * @return the value of foreo_trans.trans_channel
	 *
	 * @mbg.generated
	 */
	public String getTransChannel() {
		return transChannel;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.trans_channel
	 *
	 * @param transChannel the value for foreo_trans.trans_channel
	 *
	 * @mbg.generated
	 */
	public void setTransChannel(String transChannel) {
		this.transChannel = transChannel == null ? null : transChannel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.third_trade_req_id
	 *
	 * @return the value of foreo_trans.third_trade_req_id
	 *
	 * @mbg.generated
	 */
	public String getThirdTradeReqId() {
		return thirdTradeReqId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.third_trade_req_id
	 *
	 * @param thirdTradeReqId the value for foreo_trans.third_trade_req_id
	 *
	 * @mbg.generated
	 */
	public void setThirdTradeReqId(String thirdTradeReqId) {
		this.thirdTradeReqId = thirdTradeReqId == null ? null : thirdTradeReqId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.third_trade_res_id
	 *
	 * @return the value of foreo_trans.third_trade_res_id
	 *
	 * @mbg.generated
	 */
	public String getThirdTradeResId() {
		return thirdTradeResId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.third_trade_res_id
	 *
	 * @param thirdTradeResId the value for foreo_trans.third_trade_res_id
	 *
	 * @mbg.generated
	 */
	public void setThirdTradeResId(String thirdTradeResId) {
		this.thirdTradeResId = thirdTradeResId == null ? null : thirdTradeResId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.third_trade_req_time
	 *
	 * @return the value of foreo_trans.third_trade_req_time
	 *
	 * @mbg.generated
	 */
	public Date getThirdTradeReqTime() {
		return thirdTradeReqTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.third_trade_req_time
	 *
	 * @param thirdTradeReqTime the value for foreo_trans.third_trade_req_time
	 *
	 * @mbg.generated
	 */
	public void setThirdTradeReqTime(Date thirdTradeReqTime) {
		this.thirdTradeReqTime = thirdTradeReqTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.third_trade_res_time
	 *
	 * @return the value of foreo_trans.third_trade_res_time
	 *
	 * @mbg.generated
	 */
	public Date getThirdTradeResTime() {
		return thirdTradeResTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.third_trade_res_time
	 *
	 * @param thirdTradeResTime the value for foreo_trans.third_trade_res_time
	 *
	 * @mbg.generated
	 */
	public void setThirdTradeResTime(Date thirdTradeResTime) {
		this.thirdTradeResTime = thirdTradeResTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.third_trade_callback_amount
	 *
	 * @return the value of foreo_trans.third_trade_callback_amount
	 *
	 * @mbg.generated
	 */
	public String getThirdTradeCallbackAmount() {
		return thirdTradeCallbackAmount;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.third_trade_callback_amount
	 *
	 * @param thirdTradeCallbackAmount the value for foreo_trans.third_trade_callback_amount
	 *
	 * @mbg.generated
	 */
	public void setThirdTradeCallbackAmount(String thirdTradeCallbackAmount) {
		this.thirdTradeCallbackAmount = thirdTradeCallbackAmount == null ? null : thirdTradeCallbackAmount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.third_trade_callback_time
	 *
	 * @return the value of foreo_trans.third_trade_callback_time
	 *
	 * @mbg.generated
	 */
	public Date getThirdTradeCallbackTime() {
		return thirdTradeCallbackTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.third_trade_callback_time
	 *
	 * @param thirdTradeCallbackTime the value for foreo_trans.third_trade_callback_time
	 *
	 * @mbg.generated
	 */
	public void setThirdTradeCallbackTime(Date thirdTradeCallbackTime) {
		this.thirdTradeCallbackTime = thirdTradeCallbackTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.create_time
	 *
	 * @return the value of foreo_trans.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.create_time
	 *
	 * @param createTime the value for foreo_trans.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans.trans_status
	 *
	 * @return the value of foreo_trans.trans_status
	 *
	 * @mbg.generated
	 */
	public String getTransStatus() {
		return transStatus;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans.trans_status
	 *
	 * @param transStatus the value for foreo_trans.trans_status
	 *
	 * @mbg.generated
	 */
	public void setTransStatus(String transStatus) {
		this.transStatus = transStatus == null ? null : transStatus.trim();
	}
}
