package com.gulimall.pay.entity;

import java.util.Date;

public class TransDetailDo {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans_detail.id
	 *
	 * @mbg.generated
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans_detail.trans_id
	 *
	 * @mbg.generated
	 */
	private String transId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans_detail.detail_type
	 *
	 * @mbg.generated
	 */
	private String detailType;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans_detail.create_time
	 *
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column foreo_trans_detail.trans_detail
	 *
	 * @mbg.generated
	 */
	private String transDetail;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans_detail.id
	 *
	 * @return the value of foreo_trans_detail.id
	 *
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans_detail.id
	 *
	 * @param id the value for foreo_trans_detail.id
	 *
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans_detail.trans_id
	 *
	 * @return the value of foreo_trans_detail.trans_id
	 *
	 * @mbg.generated
	 */
	public String getTransId() {
		return transId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans_detail.trans_id
	 *
	 * @param transId the value for foreo_trans_detail.trans_id
	 *
	 * @mbg.generated
	 */
	public void setTransId(String transId) {
		this.transId = transId == null ? null : transId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans_detail.detail_type
	 *
	 * @return the value of foreo_trans_detail.detail_type
	 *
	 * @mbg.generated
	 */
	public String getDetailType() {
		return detailType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans_detail.detail_type
	 *
	 * @param detailType the value for foreo_trans_detail.detail_type
	 *
	 * @mbg.generated
	 */
	public void setDetailType(String detailType) {
		this.detailType = detailType == null ? null : detailType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans_detail.create_time
	 *
	 * @return the value of foreo_trans_detail.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans_detail.create_time
	 *
	 * @param createTime the value for foreo_trans_detail.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column foreo_trans_detail.trans_detail
	 *
	 * @return the value of foreo_trans_detail.trans_detail
	 *
	 * @mbg.generated
	 */
	public String getTransDetail() {
		return transDetail;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column foreo_trans_detail.trans_detail
	 *
	 * @param transDetail the value for foreo_trans_detail.trans_detail
	 *
	 * @mbg.generated
	 */
	public void setTransDetail(String transDetail) {
		this.transDetail = transDetail == null ? null : transDetail.trim();
	}
}