server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: gulimall_ware_router
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 用户服务路由
        - id: gulimall_member_router
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 三方服务路由
        - id: gulimall_thirdparty_router
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 商品服务路由
        - id: gulimall_product_api_router
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 人人路由
        - id: renren_fast_router
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        # 搜索 服务 路由
        - id: gulimall_search_router
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        #          认证路由
        - id: gulimall_search_router
          uri: lb://gulimall-auth
          predicates:
            - Host=auth.gulimall.com
        - id: gulimall_cart_router
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com
        # 商品服务路由
        - id: gulimall_host_router
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,www.gulimall.com,item.gulimall.com

