server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: gulimall_ware_router
          uri: lb://gulimall-member
            predicates:
              - Path=/api/ware/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        # 用户服务路由
        - id: gulimall_member_router
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 三方服务路由
        - id: gulimall_thirdparty_router
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 商品服务路由
        - id: gulimall_product_router
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 人人路由
        - id: renren_fast_router
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}