server:
  port: 30001
  servlet:
    context-path: /thirdparty
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4FzoEDNaYe7bWpBonuMg
      secret-key: LWXUGgLsdkZV5SisrMPCfhrjvDiaf3
      oss:
        bucket: my-gmall-oss
        endpoint: oss-cn-chengdu.aliyuncs.com

gulimall:
  sms:
    host: https://smsmsgs.market.alicloudapi.com
    path: /sms/
    appcode: 3354d6a7e73f4131b79410e0e0cdcce9
    sign: 175622
    skin: 1
